export enum Message {
  EVENT_GET = 'EVENT_GET',
  EVENT_SET = 'EVENT_SET',
  EVENT_GET_RESPONSE = 'EVENT_GET_RESPONSE',
  EVENT_JSONRPC_REQUEST = 'EVENT_JSONRPC_REQUEST',
  EVENT_JSONRPC_RESPONSE = 'EVENT_JSONRPC_RESPONSE',
  EVENT_JSONRPC_ERROR_RESPONSE = 'EVENT_JSONRPC_ERROR_RESPONSE',
  EVENT_PROVIDER_EVENT = 'EVENT_PROVIDER_EVENT',
}
