export enum Message {
  EVENT_JSONRPC_REQUEST = 'EVENT_JSONRPC_REQUEST',
  EVENT_JSONRPC_RESPONSE = 'EVENT_JSONRPC_RESPONSE',
  EVENT_JSONRPC_ERROR_RESPONSE = 'EVENT_JSONRPC_ERROR_RESPONSE',
  EVENT_PROVIDER_EVENT = 'EVENT_PROVIDER_EVENT',
}
